# Repository required for jekyll to generate the site
repository: mtempleheald/mtempleheald.github.io


# GitHub defaults which can be overridden, more listed here https://help.github.com/articles/repository-metadata-on-github-pages/
github:
  build_revision: 
  repository_url: 
  repository_name: 
  owner_name: 
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end


# Set variables accepted by the theme
title: mtempleheald.github.io
description: Assorted technology-related musings, investigations and projects
lang: en-GB
